
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
<?xml version="1.0" encoding="UTF-8"?>
<project> xmlns="" xmlns:xsi=" "
	xsi:schemaLocation="http://maven.apache.org/POM/2.6.3 https://maven.apache.org/xsd/maven-2.6.3.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.7</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>ru.skypro</groupId>
	<artifactId>Calculator</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Calculator</name>
	<description>Demo project for Spring Boot</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<!-- https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit -->
		<dependency>
			<groupId>com.squareup.retrofit2</groupId>
			<artifactId>retrofit</artifactId>
			<version>2.11.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>


	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
		<scope>test</scope>
	</dependency>

	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-dependency-plugin</artifactId>
		<executions>
			<execution>
				<goals>
					<goal>properties</goal>
				</goals>
			</execution>
		</executions>
	</plugin>

	<!DOCTYPE HTML>
	<head>
		<title>Ght</title>
	</head>
	<body>
		<a href="@{/login}">test</a>
	</body>


		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-surefire-plugin</artifactId>
		<configuration>
			<argLine>@{argLine} -javaagent:${org.mockito:mockito-core:jar}</argLine>
		</configuration>


	java.lang.IllegalArgumentException: 'uriTemplate' must not be null
	at org.springframework.util.Assert.hasText(Assert.java:168) ~[spring-core-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.util.UriTemplate.<init> (UriTemplate.java:61) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
		at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:134) ~[spring-hateoas-0.20.0.RELEASE.jar:na]
		at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:172) ~[spring-hateoas-0.20.0.RELEASE.jar:na]

	</project>